#!/usr/bin/env node
// gen-methods.js — snapshot poe2-kb/crafting/methods.json → method-data.js (committed).
//
// Same pattern the recipe layer used, and for the same reason: the server is zero-dep and must
// not read a sibling repo at runtime. The KB owns the catalog (it is sourced, patch-tagged data);
// this vendors it in and VALIDATES it, so a malformed catalog fails here at generate time rather
// than producing silently-wrong odds in a live plan.
//
// The catalog is the engine's coverage contract: craft-plan.js must implement every move with
// search:true, or name it in UNSUPPORTED with a reason. plan-coverage-test.js enforces that.
//
// Usage: node gen-methods.js

const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "..", "poe2-kb", "crafting", "methods.json");
const OUT = path.join(__dirname, "method-data.js");

const KINDS = new Set([
  "upgrade_add", "add", "replace", "remove", "guarantee_add", "reveal_pick",
  "fracture", "foresee", "reroll_values", "corrupt", "socket", "quality", "unique_chance", "copy",
]);
const PHASES = new Set(["start", "guarantee", "fill", "fix", "lock", "finish"]);

const cat = JSON.parse(fs.readFileSync(SRC, "utf8"));
const errs = [];
const seen = new Set();

if (!Array.isArray(cat.moves) || !cat.moves.length) errs.push("catalog has no moves");
for (const m of cat.moves || []) {
  const at = `move "${m.id || "(no id)"}"`;
  if (!m.id) errs.push(`${at}: missing id`);
  if (seen.has(m.id)) errs.push(`${at}: duplicate id`);
  seen.add(m.id);
  if (!m.name) errs.push(`${at}: missing name`);
  if (!PHASES.has(m.phase)) errs.push(`${at}: unknown phase "${m.phase}"`);
  if (!m.effect || !KINDS.has(m.effect.kind)) errs.push(`${at}: unknown effect kind "${m.effect && m.effect.kind}"`);
  if (!m.currency) errs.push(`${at}: missing currency`);
  if (m.search !== true && m.search !== false) errs.push(`${at}: search must be true or false`);
}
if (errs.length) {
  console.error("methods.json is invalid — refusing to generate:");
  for (const e of errs) console.error("  - " + e);
  process.exit(1);
}

const searchable = cat.moves.filter((m) => m.search);
const body =
  "// GENERATED by gen-methods.js from poe2-kb/crafting/methods.json — DO NOT EDIT.\n" +
  `// patch ${cat.patch} (${cat.league}) — ${cat.moves.length} moves, ${searchable.length} searchable.\n` +
  "// The KB owns this data. To change a move, change it there and re-run gen-methods.js.\n" +
  "module.exports = " + JSON.stringify({
    generated: new Date().toISOString(),
    patch: cat.patch,
    league: cat.league,
    moves: cat.moves,
  }, null, 2) + ";\n";

fs.writeFileSync(OUT, body, "utf8");
console.log(`method-data.js written — ${cat.moves.length} moves (${searchable.length} searchable), patch ${cat.patch}`);
