-- gen-craft-data.lua — extract the craftable mod pool from Path of Building's
-- bundled game data (Data/ModItem.lua, Data/Essence.lua, Data/Bases/*.lua —
-- auto-generated by PoB from GGG's files, "(c) Grinding Gear Games") into a single
-- repo file craft-data.js that the VM-hosted server bakes into its image.
--
--   luajit gen-craft-data.lua              (run on the Main PC where PoB is installed)
--   POB_DIR="..." luajit gen-craft-data.lua   (override PoB location)
--
-- Parsed with LuaJIT (not regex) so the numbers are exact — mod weights/tiers/groups
-- are the crafter's whole reason to exist. Re-run after a PoB data / league update;
-- do not hand-edit craft-data.js. This is the local, no-network equivalent of RePoE.

local sep = package.config:sub(1,1)   -- "\" on Windows
local function join(...) return table.concat({...}, sep) end

local POB = os.getenv("POB_DIR")
if not POB or POB == "" then
  POB = join(os.getenv("APPDATA") or "", "Path of Building Community (PoE2)")
end
local DATA = join(POB, "Data")
local json = assert(dofile(join(POB, "lua", "dkjson.lua")), "dkjson not found under PoB/lua")

-- every equipment base class PoB ships (Data/Bases/*.lua). jewel/flask carry their own
-- mod pools (ModJewel/ModFlask) — their bases are included but ModItem won't populate
-- them; that's fine, the crafter's Phase 1 focuses on gear.
local BASE_FILES = {
  "amulet","axe","belt","body","boots","bow","claw","crossbow","dagger","fishing",
  "flail","flask","focus","gloves","helmet","incursionlimb","jewel","mace","quiver",
  "ring","sceptre","shield","spear","staff","sword","talisman","traptool","wand",
}

-- ── mods ──────────────────────────────────────────────────────────────────────
-- ModItem.lua returns { [key] = { type, affix, <stat lines at [1..n]>, level, group,
--   weightKey={tags}, weightVal={weights}, modTags={...} } }. Weight resolution is
--   first-matching-tag-wins over the ordered weightKey list (default last, usually 0).
local rawMods = assert(dofile(join(DATA, "ModItem.lua")), "ModItem.lua failed to load")
local mods = {}
local nMods = 0
for key, m in pairs(rawMods) do
  local stats = {}
  for i, line in ipairs(m) do stats[i] = line end   -- integer-keyed array part = stat lines
  local weights = {}
  if m.weightKey then
    for i, tag in ipairs(m.weightKey) do
      weights[i] = { tag, (m.weightVal and m.weightVal[i]) or 0 }
    end
  end
  mods[key] = {
    type   = m.type,          -- "Prefix" | "Suffix"
    name   = m.affix,         -- displayed affix name ("Sanguine", "of the Bear")
    group  = m.group,         -- mutual-exclusion group (one mod per group per item)
    ilvl   = m.level or 1,    -- minimum item level for this tier
    stats  = stats,           -- stat text lines with (min-max) roll ranges
    tags   = m.modTags or {}, -- for essence/omen tag targeting
    weights = weights,        -- ordered {tag, weight}; first tag the base has wins
  }
  nMods = nMods + 1
end

-- ── essences ──────────────────────────────────────────────────────────────────
-- name -> { type, tierLevel, mods = { [baseClass] = modKey } } (forced mod per class)
local rawEss = assert(dofile(join(DATA, "Essence.lua")), "Essence.lua failed to load")
local essences = {}
local nEss = 0
for _, e in pairs(rawEss) do
  essences[e.name] = { type = e.type, tierLevel = e.tierLevel, mods = e.mods or {} }
  nEss = nEss + 1
end

-- ── bases ───────────────────────────────────────────────────────────────────
-- name -> { class(type), tags=[...], ilvl(base req level), implicit }
local bases = {}
local nBases = 0
for _, f in ipairs(BASE_FILES) do
  local path = join(DATA, "Bases", f .. ".lua")
  local chunk = loadfile(path)
  if chunk then
    local itemBases = {}
    chunk(itemBases)   -- base files do `local itemBases = ...`
    for name, b in pairs(itemBases) do
      local tags = {}
      if type(b.tags) == "table" then
        for tag, on in pairs(b.tags) do if on then tags[#tags+1] = tag end end
        table.sort(tags)
      end
      bases[name] = {
        class    = b.type,
        tags     = tags,
        ilvl     = (b.req and b.req.level) or 0,
        implicit = b.implicit,   -- may be nil
      }
      nBases = nBases + 1
    end
  else
    io.stderr:write("skip (missing base file): " .. f .. "\n")
  end
end

-- ── emit ────────────────────────────────────────────────────────────────────
local out = {
  generated = os.date("!%Y-%m-%dT%H:%M:%SZ"),
  bases = bases,
  mods = mods,
  essences = essences,
}
local body = json.encode(out, { indent = true })

local scriptDir = arg[0]:match("^(.*)[/\\]") or "."
local outPath = join(scriptDir, "craft-data.js")
local fh = assert(io.open(outPath, "wb"))
fh:write("// AUTO-GENERATED by gen-craft-data.lua from Path of Building's Data (item data (c) GGG).\n")
fh:write("// Craftable mod pool: bases (class+tags), mods (type/tier/ilvl/group/weights/tags), essences.\n")
fh:write("// Weight resolution: first tag in a mod's `weights` list that the base has wins (default last).\n")
fh:write("// Re-run `luajit gen-craft-data.lua` after a PoB/league update; do NOT hand-edit.\n")
fh:write("module.exports = " .. body .. ";\n")
fh:close()

print(string.format("wrote craft-data.js: %d bases, %d mods, %d essences", nBases, nMods, nEss))
