// GENERATED by gen-methods.js from poe2-kb/crafting/methods.json — DO NOT EDIT.
// patch 0.5.4 (Runes of Aldur) — 60 moves, 46 searchable.
// The KB owns this data. To change a move, change it there and re-run gen-methods.js.
module.exports = {
  "generated": "2026-07-13T00:13:09.635Z",
  "patch": "0.5.4",
  "league": "Runes of Aldur",
  "moves": [
    {
      "id": "transmute",
      "name": "Orb of Transmutation",
      "phase": "start",
      "currency": "Orb of Transmutation",
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "magic",
        "adds": 1
      },
      "search": true
    },
    {
      "id": "transmute-greater",
      "name": "Greater Orb of Transmutation",
      "phase": "start",
      "currency": "Greater Orb of Transmutation",
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "magic",
        "adds": 1,
        "min_mod_level": 44
      },
      "search": true
    },
    {
      "id": "transmute-perfect",
      "name": "Perfect Orb of Transmutation",
      "phase": "start",
      "currency": "Perfect Orb of Transmutation",
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "magic",
        "adds": 1,
        "min_mod_level": 70
      },
      "search": true
    },
    {
      "id": "alchemy",
      "name": "Orb of Alchemy",
      "phase": "start",
      "currency": "Orb of Alchemy",
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 4
      },
      "search": true
    },
    {
      "id": "alchemy-sinistral",
      "name": "Orb of Alchemy + Omen of Sinistral Alchemy",
      "phase": "start",
      "currency": "Orb of Alchemy",
      "omens": [
        "Omen of Sinistral Alchemy"
      ],
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 4,
        "max_side": "prefix"
      },
      "notes": "Results in the maximum number of PREFIX modifiers (3 prefixes + 1 suffix).",
      "search": true
    },
    {
      "id": "alchemy-dextral",
      "name": "Orb of Alchemy + Omen of Dextral Alchemy",
      "phase": "start",
      "currency": "Orb of Alchemy",
      "omens": [
        "Omen of Dextral Alchemy"
      ],
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 4,
        "max_side": "suffix"
      },
      "notes": "Results in the maximum number of SUFFIX modifiers (3 suffixes + 1 prefix).",
      "search": true
    },
    {
      "id": "augment",
      "name": "Orb of Augmentation",
      "phase": "fill",
      "currency": "Orb of Augmentation",
      "requires": {
        "rarity": "magic",
        "open_affix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1
      },
      "search": true
    },
    {
      "id": "augment-greater",
      "name": "Greater Orb of Augmentation",
      "phase": "fill",
      "currency": "Greater Orb of Augmentation",
      "requires": {
        "rarity": "magic",
        "open_affix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "min_mod_level": 44
      },
      "search": true
    },
    {
      "id": "augment-perfect",
      "name": "Perfect Orb of Augmentation",
      "phase": "fill",
      "currency": "Perfect Orb of Augmentation",
      "requires": {
        "rarity": "magic",
        "open_affix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "min_mod_level": 70
      },
      "search": true
    },
    {
      "id": "regal",
      "name": "Regal Orb",
      "phase": "start",
      "currency": "Regal Orb",
      "requires": {
        "rarity": "magic"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 1
      },
      "search": true
    },
    {
      "id": "regal-greater",
      "name": "Greater Regal Orb",
      "phase": "start",
      "currency": "Greater Regal Orb",
      "requires": {
        "rarity": "magic"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 1,
        "min_mod_level": 35
      },
      "search": true
    },
    {
      "id": "regal-perfect",
      "name": "Perfect Regal Orb",
      "phase": "start",
      "currency": "Perfect Regal Orb",
      "requires": {
        "rarity": "magic"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 1,
        "min_mod_level": 50
      },
      "search": true
    },
    {
      "id": "regal-sinistral",
      "name": "Regal Orb + Omen of Sinistral Coronation",
      "phase": "start",
      "currency": "Regal Orb",
      "omens": [
        "Omen of Sinistral Coronation"
      ],
      "requires": {
        "rarity": "magic",
        "open_prefix": 1
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 1,
        "side": "prefix"
      },
      "search": true
    },
    {
      "id": "regal-dextral",
      "name": "Regal Orb + Omen of Dextral Coronation",
      "phase": "start",
      "currency": "Regal Orb",
      "omens": [
        "Omen of Dextral Coronation"
      ],
      "requires": {
        "rarity": "magic",
        "open_suffix": 1
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 1,
        "side": "suffix"
      },
      "search": true
    },
    {
      "id": "regal-homogenising",
      "name": "Regal Orb + Omen of Homogenising Coronation",
      "phase": "start",
      "currency": "Regal Orb",
      "omens": [
        "Omen of Homogenising Coronation"
      ],
      "requires": {
        "rarity": "magic"
      },
      "effect": {
        "kind": "upgrade_add",
        "to_rarity": "rare",
        "adds": 1,
        "restrict": "same_tag_as_item"
      },
      "search": true
    },
    {
      "id": "exalt",
      "name": "Exalted Orb",
      "phase": "fill",
      "currency": "Exalted Orb",
      "requires": {
        "rarity": "rare",
        "open_affix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1
      },
      "search": true
    },
    {
      "id": "exalt-greater",
      "name": "Greater Exalted Orb",
      "phase": "fill",
      "currency": "Greater Exalted Orb",
      "requires": {
        "rarity": "rare",
        "open_affix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "min_mod_level": 35
      },
      "search": true
    },
    {
      "id": "exalt-perfect",
      "name": "Perfect Exalted Orb",
      "phase": "fill",
      "currency": "Perfect Exalted Orb",
      "requires": {
        "rarity": "rare",
        "open_affix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "min_mod_level": 50
      },
      "search": true
    },
    {
      "id": "exalt-sinistral",
      "name": "Exalted Orb + Omen of Sinistral Exaltation",
      "phase": "fill",
      "currency": "Exalted Orb",
      "omens": [
        "Omen of Sinistral Exaltation"
      ],
      "requires": {
        "rarity": "rare",
        "open_prefix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "side": "prefix"
      },
      "search": true
    },
    {
      "id": "exalt-dextral",
      "name": "Exalted Orb + Omen of Dextral Exaltation",
      "phase": "fill",
      "currency": "Exalted Orb",
      "omens": [
        "Omen of Dextral Exaltation"
      ],
      "requires": {
        "rarity": "rare",
        "open_suffix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "side": "suffix"
      },
      "search": true
    },
    {
      "id": "exalt-homogenising",
      "name": "Exalted Orb + Omen of Homogenising Exaltation",
      "phase": "fill",
      "currency": "Exalted Orb",
      "omens": [
        "Omen of Homogenising Exaltation"
      ],
      "requires": {
        "rarity": "rare",
        "open_affix": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "restrict": "same_tag_as_item"
      },
      "search": true
    },
    {
      "id": "exalt-greater-omen",
      "name": "Exalted Orb + Omen of Greater Exaltation",
      "phase": "fill",
      "currency": "Exalted Orb",
      "omens": [
        "Omen of Greater Exaltation"
      ],
      "requires": {
        "rarity": "rare",
        "open_affix": 2
      },
      "effect": {
        "kind": "add",
        "adds": 2
      },
      "notes": "Two random modifiers from ONE Exalted Orb — cheaper per mod than two Exalts when two slots are open and both sides are acceptable.",
      "search": true
    },
    {
      "id": "exalt-catalysing",
      "name": "Exalted Orb + Omen of Catalysing Exaltation",
      "phase": "fill",
      "currency": "Exalted Orb",
      "omens": [
        "Omen of Catalysing Exaltation"
      ],
      "requires": {
        "rarity": "rare",
        "open_affix": 1,
        "item_class": "jewellery",
        "quality": 1
      },
      "effect": {
        "kind": "add",
        "adds": 1,
        "restrict": "catalysed_tag",
        "consumes_quality": true
      },
      "notes": "Consumes all Catalyst Quality to bias the added modifier toward the catalyst's type. Jewellery only.",
      "search": true
    },
    {
      "id": "chaos",
      "name": "Chaos Orb",
      "phase": "fix",
      "currency": "Chaos Orb",
      "requires": {
        "rarity": "rare"
      },
      "effect": {
        "kind": "replace",
        "pick": "random"
      },
      "search": true
    },
    {
      "id": "chaos-greater",
      "name": "Greater Chaos Orb",
      "phase": "fix",
      "currency": "Greater Chaos Orb",
      "requires": {
        "rarity": "rare"
      },
      "effect": {
        "kind": "replace",
        "pick": "random",
        "min_mod_level": 35
      },
      "search": true
    },
    {
      "id": "chaos-perfect",
      "name": "Perfect Chaos Orb",
      "phase": "fix",
      "currency": "Perfect Chaos Orb",
      "requires": {
        "rarity": "rare"
      },
      "effect": {
        "kind": "replace",
        "pick": "random",
        "min_mod_level": 50
      },
      "search": true
    },
    {
      "id": "chaos-whittling",
      "name": "Chaos Orb + Omen of Whittling",
      "phase": "fix",
      "currency": "Chaos Orb",
      "omens": [
        "Omen of Whittling"
      ],
      "requires": {
        "rarity": "rare"
      },
      "effect": {
        "kind": "replace",
        "pick": "lowest_level"
      },
      "notes": "Removes the LOWEST-level modifier — protects your high tiers while churning the junk.",
      "search": true
    },
    {
      "id": "chaos-sinistral-erasure",
      "name": "Chaos Orb + Omen of Sinistral Erasure",
      "phase": "fix",
      "currency": "Chaos Orb",
      "omens": [
        "Omen of Sinistral Erasure"
      ],
      "requires": {
        "rarity": "rare",
        "has_prefix": 1
      },
      "effect": {
        "kind": "replace",
        "pick": "random",
        "remove_side": "prefix"
      },
      "notes": "Removes only a PREFIX — protects every suffix you have hit.",
      "search": true
    },
    {
      "id": "chaos-dextral-erasure",
      "name": "Chaos Orb + Omen of Dextral Erasure",
      "phase": "fix",
      "currency": "Chaos Orb",
      "omens": [
        "Omen of Dextral Erasure"
      ],
      "requires": {
        "rarity": "rare",
        "has_suffix": 1
      },
      "effect": {
        "kind": "replace",
        "pick": "random",
        "remove_side": "suffix"
      },
      "notes": "Removes only a SUFFIX — protects every prefix you have hit.",
      "search": true
    },
    {
      "id": "annul",
      "name": "Orb of Annulment",
      "phase": "fix",
      "currency": "Orb of Annulment",
      "requires": {
        "has_affix": 1
      },
      "effect": {
        "kind": "remove",
        "removes": 1,
        "pick": "random"
      },
      "destructive": true,
      "search": true
    },
    {
      "id": "annul-sinistral",
      "name": "Orb of Annulment + Omen of Sinistral Annulment",
      "phase": "fix",
      "currency": "Orb of Annulment",
      "omens": [
        "Omen of Sinistral Annulment"
      ],
      "requires": {
        "has_prefix": 1
      },
      "effect": {
        "kind": "remove",
        "removes": 1,
        "pick": "random",
        "remove_side": "prefix"
      },
      "destructive": true,
      "search": true
    },
    {
      "id": "annul-dextral",
      "name": "Orb of Annulment + Omen of Dextral Annulment",
      "phase": "fix",
      "currency": "Orb of Annulment",
      "omens": [
        "Omen of Dextral Annulment"
      ],
      "requires": {
        "has_suffix": 1
      },
      "effect": {
        "kind": "remove",
        "removes": 1,
        "pick": "random",
        "remove_side": "suffix"
      },
      "destructive": true,
      "search": true
    },
    {
      "id": "annul-greater",
      "name": "Orb of Annulment + Omen of Greater Annulment",
      "phase": "fix",
      "currency": "Orb of Annulment",
      "omens": [
        "Omen of Greater Annulment"
      ],
      "requires": {
        "has_affix": 2
      },
      "effect": {
        "kind": "remove",
        "removes": 2,
        "pick": "random"
      },
      "destructive": true,
      "notes": "Removes TWO random modifiers. Only sane when the item is mostly junk you want gone.",
      "search": true
    },
    {
      "id": "annul-light",
      "name": "Orb of Annulment + Omen of Light",
      "phase": "fix",
      "currency": "Orb of Annulment",
      "omens": [
        "Omen of Light"
      ],
      "requires": {
        "has_desecrated": 1
      },
      "effect": {
        "kind": "remove",
        "removes": 1,
        "pick": "desecrated"
      },
      "notes": "Removes only DESECRATED modifiers — the clean way to undo a bad Well of Souls reveal.",
      "search": true
    },
    {
      "id": "essence-magic",
      "name": "Essence (Lesser / Standard / Greater) on a Magic item",
      "phase": "guarantee",
      "currency": "<essence>",
      "requires": {
        "rarity": "magic",
        "group_absent": "essence_group"
      },
      "effect": {
        "kind": "guarantee_add",
        "to_rarity": "rare",
        "adds": 1
      },
      "notes": "Upgrades Magic → Rare and adds the essence's guaranteed modifier. One essence per item. Cannot add a modifier whose group is already on the item. Tiers differ only in rolled value / minimum modifier level: Lesser < Standard < Greater.",
      "search": true
    },
    {
      "id": "essence-rare",
      "name": "Perfect / Corrupted Essence on a Rare item",
      "phase": "guarantee",
      "currency": "<perfect essence>",
      "requires": {
        "rarity": "rare",
        "group_absent": "essence_group"
      },
      "effect": {
        "kind": "guarantee_add",
        "adds": 1,
        "removes": 1,
        "pick": "random"
      },
      "destructive": true,
      "notes": "Removes a RANDOM modifier, then adds the guaranteed one — it can eat a mod you wanted.",
      "search": true
    },
    {
      "id": "essence-rare-sinistral",
      "name": "Perfect / Corrupted Essence + Omen of Sinistral Crystallisation",
      "phase": "guarantee",
      "currency": "<perfect essence>",
      "omens": [
        "Omen of Sinistral Crystallisation"
      ],
      "requires": {
        "rarity": "rare",
        "has_prefix": 1,
        "group_absent": "essence_group"
      },
      "effect": {
        "kind": "guarantee_add",
        "adds": 1,
        "removes": 1,
        "pick": "random",
        "remove_side": "prefix"
      },
      "notes": "Steers the essence's removal to a PREFIX — the way to use a Perfect essence without risking your suffixes.",
      "search": true
    },
    {
      "id": "essence-rare-dextral",
      "name": "Perfect / Corrupted Essence + Omen of Dextral Crystallisation",
      "phase": "guarantee",
      "currency": "<perfect essence>",
      "omens": [
        "Omen of Dextral Crystallisation"
      ],
      "requires": {
        "rarity": "rare",
        "has_suffix": 1,
        "group_absent": "essence_group"
      },
      "effect": {
        "kind": "guarantee_add",
        "adds": 1,
        "removes": 1,
        "pick": "random",
        "remove_side": "suffix"
      },
      "notes": "Steers the essence's removal to a SUFFIX.",
      "search": true
    },
    {
      "id": "desecrate",
      "name": "Abyssal Bone (Well of Souls)",
      "phase": "guarantee",
      "currency": "Abyssal Bone",
      "requires": {
        "rarity": "rare",
        "open_affix": 1,
        "desecrated_absent": true
      },
      "effect": {
        "kind": "reveal_pick",
        "reveal": 3,
        "keep": 1,
        "desecrated": true
      },
      "notes": "Reveals 3 desecrated modifiers, you keep 1. Desecrated mods cannot be added by any other currency.",
      "search": true
    },
    {
      "id": "desecrate-sinistral",
      "name": "Abyssal Bone + Omen of Sinistral Necromancy",
      "phase": "guarantee",
      "currency": "Abyssal Bone",
      "omens": [
        "Omen of Sinistral Necromancy"
      ],
      "requires": {
        "rarity": "rare",
        "open_prefix": 1,
        "desecrated_absent": true
      },
      "effect": {
        "kind": "reveal_pick",
        "reveal": 3,
        "keep": 1,
        "desecrated": true,
        "side": "prefix"
      },
      "search": true
    },
    {
      "id": "desecrate-dextral",
      "name": "Abyssal Bone + Omen of Dextral Necromancy",
      "phase": "guarantee",
      "currency": "Abyssal Bone",
      "omens": [
        "Omen of Dextral Necromancy"
      ],
      "requires": {
        "rarity": "rare",
        "open_suffix": 1,
        "desecrated_absent": true
      },
      "effect": {
        "kind": "reveal_pick",
        "reveal": 3,
        "keep": 1,
        "desecrated": true,
        "side": "suffix"
      },
      "search": true
    },
    {
      "id": "desecrate-echoes",
      "name": "Abyssal Bone + Omen of Abyssal Echoes",
      "phase": "guarantee",
      "currency": "Abyssal Bone",
      "omens": [
        "Omen of Abyssal Echoes"
      ],
      "requires": {
        "rarity": "rare",
        "open_affix": 1,
        "desecrated_absent": true
      },
      "effect": {
        "kind": "reveal_pick",
        "reveal": 3,
        "keep": 1,
        "desecrated": true,
        "reroll_options": 1
      },
      "notes": "Reroll the 3 revealed options once — roughly doubles the chance the mod you want is offered.",
      "search": true
    },
    {
      "id": "desecrate-faction",
      "name": "Abyssal Bone + Omen of the Blackblooded / the Liege / the Sovereign",
      "phase": "guarantee",
      "currency": "Abyssal Bone",
      "omens": [
        "Omen of the Blackblooded",
        "Omen of the Liege",
        "Omen of the Sovereign"
      ],
      "requires": {
        "rarity": "rare",
        "open_affix": 1,
        "item_class": "weapon_or_jewellery",
        "desecrated_absent": true
      },
      "effect": {
        "kind": "reveal_pick",
        "reveal": 3,
        "keep": 1,
        "desecrated": true,
        "faction": "kurgal|amanamu|ulaman"
      },
      "notes": "Guarantees a random modifier of ONE faction (Blackblooded=Kurgal, Liege=Amanamu, Sovereign=Ulaman) — narrows the reveal pool to that faction. Weapons and jewellery only.",
      "search": true
    },
    {
      "id": "desecrate-putrefaction",
      "name": "Abyssal Bone + Omen of Putrefaction",
      "phase": "guarantee",
      "currency": "Abyssal Bone",
      "omens": [
        "Omen of Putrefaction"
      ],
      "requires": {
        "rarity": "rare"
      },
      "effect": {
        "kind": "reveal_pick",
        "replaces_all": true,
        "reveal": 6,
        "desecrated": true,
        "corrupts": true
      },
      "destructive": true,
      "notes": "Replaces ALL modifiers with up to 6 unrevealed desecrated mods AND corrupts the item. Total reroll, no undo.",
      "search": true
    },
    {
      "id": "fracture",
      "name": "Fracturing Orb",
      "phase": "lock",
      "currency": "Fracturing Orb",
      "requires": {
        "rarity": "rare",
        "has_affix": 4
      },
      "effect": {
        "kind": "fracture",
        "pick": "random"
      },
      "notes": "Locks a RANDOM modifier (you cannot choose which) so Chaos/Annul can never remove it. Needs 4+ modifiers.",
      "search": true
    },
    {
      "id": "hinekora",
      "name": "Hinekora's Lock",
      "phase": "lock",
      "currency": "Hinekora's Lock",
      "requires": {},
      "effect": {
        "kind": "foresee"
      },
      "notes": "Foresee the result of the NEXT currency used, and decline it if it is bad. Turns any single random slam into a re-rollable one: the cost of a hit becomes (lock + orb) per look instead of a destroyed item. The single most important move the engine must not forget on a high-value item.",
      "search": true
    },
    {
      "id": "divine",
      "name": "Divine Orb",
      "phase": "finish",
      "currency": "Divine Orb",
      "requires": {
        "has_affix": 1
      },
      "effect": {
        "kind": "reroll_values"
      },
      "notes": "Rerolls numeric values only — never changes which modifiers are present. Never a path to a missing mod.",
      "search": false
    },
    {
      "id": "divine-sanctification",
      "name": "Divine Orb + Omen of Sanctification",
      "phase": "finish",
      "currency": "Divine Orb",
      "omens": [
        "Omen of Sanctification"
      ],
      "requires": {
        "rarity": "rare"
      },
      "effect": {
        "kind": "reroll_values",
        "sanctify": true
      },
      "notes": "Sanctifies the Rare instead of rerolling values.",
      "search": false
    },
    {
      "id": "divine-blessed",
      "name": "Divine Orb + Omen of the Blessed",
      "phase": "finish",
      "currency": "Divine Orb",
      "omens": [
        "Omen of the Blessed"
      ],
      "requires": {},
      "effect": {
        "kind": "reroll_values",
        "implicits_only": true
      },
      "search": false
    },
    {
      "id": "vaal",
      "name": "Vaal Orb",
      "phase": "finish",
      "currency": "Vaal Orb",
      "requires": {},
      "effect": {
        "kind": "corrupt"
      },
      "destructive": true,
      "notes": "Unpredictable change + Corrupts (no further modification). Terminal move — only ever last.",
      "search": false
    },
    {
      "id": "vaal-corruption",
      "name": "Vaal Orb + Omen of Corruption",
      "phase": "finish",
      "currency": "Vaal Orb",
      "omens": [
        "Omen of Corruption"
      ],
      "requires": {},
      "effect": {
        "kind": "corrupt",
        "always_changes": true
      },
      "destructive": true,
      "search": false
    },
    {
      "id": "artificer",
      "name": "Artificer's Orb",
      "phase": "finish",
      "currency": "Artificer's Orb",
      "requires": {
        "item_class": "weapon_or_armour"
      },
      "effect": {
        "kind": "socket",
        "adds_socket": 1
      },
      "search": false
    },
    {
      "id": "socket-rune",
      "name": "Socket a Rune / Soul Core",
      "phase": "finish",
      "currency": "<rune or soul core>",
      "requires": {
        "open_socket": 1
      },
      "effect": {
        "kind": "socket",
        "fills_socket": 1
      },
      "notes": "Runes and Soul Cores add their stat OUTSIDE the affix pool — they do not consume prefix/suffix slots, so they are pure addition to any finished item. See crafting/reference/{runes,soul-cores}.md.",
      "search": false
    },
    {
      "id": "aldurs-legacy",
      "name": "Aldur's Legacy (rune extraction)",
      "phase": "finish",
      "currency": "Aldur's Legacy",
      "requires": {
        "rarity": "unique",
        "item_class": "kalguuran_or_ezomyte",
        "open_socket": 1,
        "not_corrupted": true
      },
      "effect": {
        "kind": "socket",
        "destroys_item": true,
        "produces": "Legacy of X rune"
      },
      "destructive": true,
      "notes": "The 0.5 league mechanic: destroys a non-corrupted Kalguuran/Ezomyte unique to create a base-type-locked rune carrying a scaled-down version of its power. See crafting/reference/aldurs-legacy.md.",
      "search": false
    },
    {
      "id": "catalyst",
      "name": "Catalyst (quality on jewellery)",
      "phase": "finish",
      "currency": "<catalyst>",
      "requires": {
        "item_class": "jewellery"
      },
      "effect": {
        "kind": "quality",
        "biases_tag": true
      },
      "notes": "Quality on jewellery biases a modifier TYPE. Only converts into odds when spent via Omen of Catalysing Exaltation (see exalt-catalysing).",
      "search": false
    },
    {
      "id": "quality-martial",
      "name": "Blacksmith's Whetstone / Arcanist's Etcher / Armourer's Scrap",
      "phase": "finish",
      "currency": "<quality currency>",
      "requires": {},
      "effect": {
        "kind": "quality"
      },
      "notes": "Quality on gear scales the base's local stats, never the affix pool.",
      "search": false
    },
    {
      "id": "chance",
      "name": "Orb of Chance",
      "phase": "start",
      "currency": "Orb of Chance",
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "unique_chance",
        "may_destroy": true
      },
      "destructive": true,
      "search": false
    },
    {
      "id": "chance-safe",
      "name": "Orb of Chance + Omen of Chance",
      "phase": "start",
      "currency": "Orb of Chance",
      "omens": [
        "Omen of Chance"
      ],
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "unique_chance",
        "may_destroy": false
      },
      "search": false
    },
    {
      "id": "chance-ancients",
      "name": "Orb of Chance + Omen of the Ancients",
      "phase": "start",
      "currency": "Orb of Chance",
      "omens": [
        "Omen of the Ancients"
      ],
      "requires": {
        "rarity": "normal"
      },
      "effect": {
        "kind": "unique_chance",
        "guaranteed": true,
        "random_unique_of_class": true
      },
      "notes": "Guarantees a random Unique of the same item class — the only deterministic route to a unique.",
      "search": false
    },
    {
      "id": "mirror",
      "name": "Mirror of Kalandra",
      "phase": "finish",
      "currency": "Mirror of Kalandra",
      "requires": {},
      "effect": {
        "kind": "copy"
      },
      "notes": "Copies the item. Never part of a crafting path — it is what you do to a finished mirror-tier item.",
      "search": false
    }
  ]
};
